"""
test_pipeline.py — Unit tests for orchestration/pipeline.py

Tests the retry cap, happy-path flow, and manager agent integration.
All agent calls use stubs — no Bob API calls needed.

Run with: pytest orchestration/test_pipeline.py -v
"""
import json
import os
import sys
import tempfile
import pytest

# Path setup
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(REPO_ROOT, "orchestration"))
sys.path.insert(0, os.path.join(REPO_ROOT, "agents", "manager_agent"))
sys.path.insert(0, os.path.join(REPO_ROOT, "agents", "reflection_agent"))

import pipeline


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def make_fresh_task(request="Add rate limiting"):
    return pipeline.initialize_task(request, task_id="test_task_001")


# ──────────────────────────────────────────────────────────────────────────────
# initialize_task
# ──────────────────────────────────────────────────────────────────────────────

def test_initialize_task_has_required_fields():
    task = make_fresh_task()
    required = [
        "task_id", "feature_request", "acceptance_criteria", "scoped_files",
        "status", "current_agent", "history", "code_diff", "test_results",
        "review_result", "retry_count"
    ]
    for field in required:
        assert field in task, f"Missing field: {field}"


def test_initialize_task_defaults():
    task = make_fresh_task("My feature")
    assert task["feature_request"] == "My feature"
    assert task["status"] == "pending"
    assert task["retry_count"] == 0
    assert task["history"] == []
    assert task["code_diff"] is None


def test_initialize_task_custom_id():
    task = pipeline.initialize_task("Feature X", task_id="task_custom_99")
    assert task["task_id"] == "task_custom_99"


def test_initialize_task_autogenerated_id():
    task = pipeline.initialize_task("Feature Y")
    assert task["task_id"].startswith("task_")
    assert len(task["task_id"]) > 5


# ──────────────────────────────────────────────────────────────────────────────
# append_history
# ──────────────────────────────────────────────────────────────────────────────

def test_append_history_adds_entry():
    task = make_fresh_task()
    task = pipeline.append_history(task, "pm_agent", "criteria defined", True)
    assert len(task["history"]) == 1
    entry = task["history"][0]
    assert entry["agent"] == "pm_agent"
    assert entry["output_summary"] == "criteria defined"
    assert entry["success"] is True
    assert "timestamp" in entry


def test_append_history_multiple_entries():
    task = make_fresh_task()
    task = pipeline.append_history(task, "pm_agent", "step 1", True)
    task = pipeline.append_history(task, "architect_agent", "step 2", True)
    task = pipeline.append_history(task, "coding_agent", "step 3", False)
    assert len(task["history"]) == 3
    assert task["history"][2]["success"] is False


# ──────────────────────────────────────────────────────────────────────────────
# Retry cap
# ──────────────────────────────────────────────────────────────────────────────

def test_retry_cap_blocks_at_max_retries(monkeypatch, tmp_path):
    """Pipeline must set status=blocked and stop looping when retry_count == MAX_RETRIES."""
    # Redirect file outputs to temp dir
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    # Make review always fail
    def failing_review(task):
        task["review_result"] = {"passed": False, "findings": [
            {"checklist_item": "missing input validation", "file": "f.py",
             "line": 1, "severity": "high", "description": "test"}
        ]}
        pipeline.append_history(task, "review_agent", "rejected (test)", False)
        for entry in reversed(task["history"]):
            if entry["agent"] == "coding_agent" and entry["success"] is True:
                entry["success"] = False
                break
        task["status"] = "needs_retry"
        task["current_agent"] = "manager_agent"
        return task

    monkeypatch.setattr(pipeline, "call_review_agent", failing_review)

    task = pipeline.run_pipeline("Test feature for retry cap", task_id="test_retry")
    assert task["status"] == "blocked"
    assert task["retry_count"] == pipeline.MAX_RETRIES


def test_retry_cap_value_is_two():
    """MAX_RETRIES must be 2 as specified in the hackathon plan."""
    assert pipeline.MAX_RETRIES == 2


# ──────────────────────────────────────────────────────────────────────────────
# Happy path
# ──────────────────────────────────────────────────────────────────────────────

def test_happy_path_status_awaiting_approval(monkeypatch, tmp_path):
    """When all agents succeed, final status should be awaiting_human_approval."""
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    task = pipeline.run_pipeline("Happy path feature", task_id="test_happy")
    assert task["status"] == "awaiting_human_approval"
    assert task["retry_count"] == 0


def test_happy_path_history_has_all_agents(monkeypatch, tmp_path):
    """History should contain entries for all 5 core agents + manager."""
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    task = pipeline.run_pipeline("History check feature", task_id="test_history")
    agents_in_history = [e["agent"] for e in task["history"]]
    for agent in ["pm_agent", "architect_agent", "coding_agent", "testing_agent", "review_agent", "manager_agent"]:
        assert agent in agents_in_history, f"Missing agent in history: {agent}"


def test_happy_path_code_diff_is_set(monkeypatch, tmp_path):
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    task = pipeline.run_pipeline("Diff check feature", task_id="test_diff")
    assert task["code_diff"] is not None
    assert len(task["code_diff"]) > 0


# ──────────────────────────────────────────────────────────────────────────────
# Run history (dashboard feed)
# ──────────────────────────────────────────────────────────────────────────────

def test_run_history_appended_after_pipeline(monkeypatch, tmp_path):
    """run_history.json should contain a record after each pipeline run."""
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    run_history_path = str(tmp_path / "run_history.json")
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", run_history_path)

    pipeline.run_pipeline("Run history test", task_id="test_rh")

    assert os.path.exists(run_history_path)
    with open(run_history_path) as f:
        history = json.load(f)
    assert len(history) == 1
    assert history[0]["run_id"] == 1
    assert "agent_rates" in history[0]


def test_run_history_run_ids_increment(monkeypatch, tmp_path):
    """Running the pipeline twice should produce run_ids 1 and 2."""
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    run_history_path = str(tmp_path / "run_history.json")
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", run_history_path)

    pipeline.run_pipeline("Run 1", task_id="rh_1")
    pipeline.run_pipeline("Run 2", task_id="rh_2")

    with open(run_history_path) as f:
        history = json.load(f)
    assert len(history) == 2
    assert history[0]["run_id"] == 1
    assert history[1]["run_id"] == 2


# ──────────────────────────────────────────────────────────────────────────────
# Schema validation
# ──────────────────────────────────────────────────────────────────────────────

def test_validate_task_no_crash_on_valid_task(monkeypatch, tmp_path):
    """validate_task should not raise on a well-formed task."""
    task = make_fresh_task()
    # Should not raise
    pipeline.validate_task(task, "test-stage")


def test_validate_task_prints_warning_on_invalid(capsys, monkeypatch):
    """validate_task should print a WARNING (not raise) on invalid task."""
    task = {"task_id": "x"}  # Missing most required fields
    pipeline.validate_task(task, "test-stage")
    captured = capsys.readouterr()
    # Either a warning was printed, or jsonschema isn't available — both are acceptable
    # The key assertion is that no exception was raised
    assert True  # reaching here means no exception
