"""
test_pipeline.py — Unit tests for orchestration/pipeline.py

Tests the retry cap, happy-path flow, and manager agent integration.
All agent calls use stubs — no Bob API calls needed.

Run with: pytest orchestration/test_pipeline.py -v
"""
import json
import os
import sys
import tempfile
import pytest

# Path setup
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(REPO_ROOT, "orchestration"))
sys.path.insert(0, os.path.join(REPO_ROOT, "agents", "manager_agent"))
sys.path.insert(0, os.path.join(REPO_ROOT, "agents", "reflection_agent"))

import pipeline


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def make_fresh_task(request="Add rate limiting"):
    return pipeline.initialize_task(request, task_id="test_task_001")


# ──────────────────────────────────────────────────────────────────────────────
# initialize_task
# ──────────────────────────────────────────────────────────────────────────────

def test_initialize_task_has_required_fields():
    task = make_fresh_task()
    required = [
        "task_id", "feature_request", "acceptance_criteria", "scoped_files",
        "status", "current_agent", "history", "code_diff", "test_results",
        "review_result", "retry_count"
    ]
    for field in required:
        assert field in task, f"Missing field: {field}"


def test_initialize_task_defaults():
    task = make_fresh_task("My feature")
    assert task["feature_request"] == "My feature"
    assert task["status"] == "pending"
    assert task["retry_count"] == 0
    assert task["history"] == []
    assert task["code_diff"] is None


def test_initialize_task_custom_id():
    task = pipeline.initialize_task("Feature X", task_id="task_custom_99")
    assert task["task_id"] == "task_custom_99"


def test_initialize_task_autogenerated_id():
    task = pipeline.initialize_task("Feature Y")
    assert task["task_id"].startswith("task_")
    assert len(task["task_id"]) > 5


# ──────────────────────────────────────────────────────────────────────────────
# append_history
# ──────────────────────────────────────────────────────────────────────────────

def test_append_history_adds_entry():
    task = make_fresh_task()
    task = pipeline.append_history(task, "pm_agent", "criteria defined", True)
    assert len(task["history"]) == 1
    entry = task["history"][0]
    assert entry["agent"] == "pm_agent"
    assert entry["output_summary"] == "criteria defined"
    assert entry["success"] is True
    assert "timestamp" in entry


def test_append_history_multiple_entries():
    task = make_fresh_task()
    task = pipeline.append_history(task, "pm_agent", "step 1", True)
    task = pipeline.append_history(task, "architect_agent", "step 2", True)
    task = pipeline.append_history(task, "coding_agent", "step 3", False)
    assert len(task["history"]) == 3
    assert task["history"][2]["success"] is False


# ──────────────────────────────────────────────────────────────────────────────
# Retry cap
# ──────────────────────────────────────────────────────────────────────────────

def test_retry_cap_blocks_at_max_retries(monkeypatch, tmp_path):
    """Pipeline must set status=blocked and stop looping when retry_count == MAX_RETRIES."""
    # Redirect file outputs to temp dir
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))
    # Never call the real watsonx API from tests — stub out reflection
    monkeypatch.setattr(pipeline.reflection_module, "run_reflection", lambda report: [])

    # Make review always fail
    def failing_review(task):
        task["review_result"] = {"passed": False, "findings": [
            {"checklist_item": "missing input validation", "file": "f.py",
             "line": 1, "severity": "high", "description": "test"}
        ]}
        pipeline.append_history(task, "review_agent", "rejected (test)", False)
        for entry in reversed(task["history"]):
            if entry["agent"] == "coding_agent" and entry["success"] is True:
                entry["success"] = False
                break
        task["status"] = "needs_retry"
        task["current_agent"] = "manager_agent"
        return task

    monkeypatch.setattr(pipeline, "call_review_agent", failing_review)

    task = pipeline.run_pipeline("Test feature for retry cap", task_id="test_retry")
    assert task["status"] == "blocked"
    assert task["retry_count"] == pipeline.MAX_RETRIES


def test_retry_cap_value_is_two():
    """MAX_RETRIES must be 2 as specified in the hackathon plan."""
    assert pipeline.MAX_RETRIES == 2


# ──────────────────────────────────────────────────────────────────────────────
# Happy path
# ──────────────────────────────────────────────────────────────────────────────

def test_happy_path_status_awaiting_approval(monkeypatch, tmp_path):
    """When all agents succeed, final status should be awaiting_human_approval."""
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    task = pipeline.run_pipeline("Happy path feature", task_id="test_happy")
    assert task["status"] == "awaiting_human_approval"
    assert task["retry_count"] == 0


def test_happy_path_history_has_all_agents(monkeypatch, tmp_path):
    """History should contain entries for all 5 core agents + manager."""
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    task = pipeline.run_pipeline("History check feature", task_id="test_history")
    agents_in_history = [e["agent"] for e in task["history"]]
    for agent in ["pm_agent", "architect_agent", "coding_agent", "testing_agent", "review_agent", "manager_agent"]:
        assert agent in agents_in_history, f"Missing agent in history: {agent}"


def test_happy_path_code_diff_is_set(monkeypatch, tmp_path):
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    task = pipeline.run_pipeline("Diff check feature", task_id="test_diff")
    assert task["code_diff"] is not None
    assert len(task["code_diff"]) > 0


# ──────────────────────────────────────────────────────────────────────────────
# Run history (dashboard feed)
# ──────────────────────────────────────────────────────────────────────────────

def test_run_history_appended_after_pipeline(monkeypatch, tmp_path):
    """run_history.json should contain a record after each pipeline run."""
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    run_history_path = str(tmp_path / "run_history.json")
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", run_history_path)

    pipeline.run_pipeline("Run history test", task_id="test_rh")

    assert os.path.exists(run_history_path)
    with open(run_history_path) as f:
        history = json.load(f)
    assert len(history) == 1
    assert history[0]["run_id"] == 1
    assert "agent_rates" in history[0]


def test_run_history_run_ids_increment(monkeypatch, tmp_path):
    """Running the pipeline twice should produce run_ids 1 and 2."""
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    run_history_path = str(tmp_path / "run_history.json")
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", run_history_path)

    pipeline.run_pipeline("Run 1", task_id="rh_1")
    pipeline.run_pipeline("Run 2", task_id="rh_2")

    with open(run_history_path) as f:
        history = json.load(f)
    assert len(history) == 2
    assert history[0]["run_id"] == 1
    assert history[1]["run_id"] == 2


# ──────────────────────────────────────────────────────────────────────────────
# Schema validation
# ──────────────────────────────────────────────────────────────────────────────

def test_validate_task_no_crash_on_valid_task(monkeypatch, tmp_path):
    """validate_task should not raise on a well-formed task."""
    task = make_fresh_task()
    # Should not raise
    pipeline.validate_task(task, "test-stage")


def test_validate_task_prints_warning_on_invalid(capsys, monkeypatch):
    """validate_task should print a WARNING (not raise) on invalid task."""
    task = {"task_id": "x"}  # Missing most required fields
    pipeline.validate_task(task, "test-stage")
    captured = capsys.readouterr()
    # Either a warning was printed, or jsonschema isn't available — both are acceptable
    # The key assertion is that no exception was raised
    assert True  # reaching here means no exception


# ──────────────────────────────────────────────────────────────────────────────
# Cross-agent conventions — Architect validation & blocked routing
# ──────────────────────────────────────────────────────────────────────────────

def test_parse_new_files_extracts_paths():
    """_parse_new_files must return all NEW FILE: paths from a plan string."""
    plan = "NEW FILE: flaskbb/middleware/rate_limit.py\nSome other text.\nNEW FILE: tests/unit/test_rate_limit.py"
    result = pipeline._parse_new_files(plan)
    assert "flaskbb/middleware/rate_limit.py" in result
    assert "tests/unit/test_rate_limit.py" in result


def test_parse_new_files_empty_plan():
    assert pipeline._parse_new_files("") == set()
    assert pipeline._parse_new_files(None) == set()


def test_parse_new_files_case_insensitive_prefix():
    """'new file:' (lowercase) should also be recognised."""
    plan = "new file: some/new/file.py"
    result = pipeline._parse_new_files(plan)
    assert "some/new/file.py" in result


def test_coding_agent_blocked_on_nonexistent_scoped_file(monkeypatch, tmp_path):
    """
    If a scoped_file doesn't exist on disk and isn't declared NEW FILE:,
    call_coding_agent must set status=blocked and append success=null history.
    """
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    # Point sample_repo_root at tmp_path so no files exist there
    import orchestration.pipeline as pl
    monkeypatch.setattr(pl, "REPO_ROOT", str(tmp_path))
    # (tmp_path/sample_repo/flaskbb/ does not exist → all paths fail existence check)

    task = pipeline.initialize_task("Test feature", task_id="test_blocked_arch")
    task["scoped_files"] = ["flaskbb/auth/views.py"]  # doesn't exist under tmp_path
    task["plan"] = "Just a plan with no NEW FILE declaration."

    task = pipeline.call_coding_agent(task)

    assert task["status"] == "blocked"
    assert task["current_agent"] == "manager_agent"
    # History entry must exist with success=None
    coding_entries = [e for e in task["history"] if e["agent"] == "coding_agent"]
    assert len(coding_entries) == 1
    assert coding_entries[0]["success"] is None
    assert "blocked" in coding_entries[0]["output_summary"]
    assert "Architect error" in coding_entries[0]["output_summary"]


def test_coding_agent_blocked_new_file_not_in_scoped_files(monkeypatch, tmp_path):
    """NEW FILE: declared in plan but missing from scoped_files → Architect error."""
    import orchestration.pipeline as pl
    monkeypatch.setattr(pl, "REPO_ROOT", str(tmp_path))
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    task = pipeline.initialize_task("Test feature", task_id="test_new_file_not_scoped")
    task["scoped_files"] = []  # new file NOT listed here
    task["plan"] = "NEW FILE: flaskbb/new_module.py\nDo something."

    task = pipeline.call_coding_agent(task)

    assert task["status"] == "blocked"
    coding_entries = [e for e in task["history"] if e["agent"] == "coding_agent"]
    assert coding_entries[0]["success"] is None
    assert "Architect error" in coding_entries[0]["output_summary"]


def test_coding_agent_blocked_new_file_already_exists(monkeypatch, tmp_path):
    """NEW FILE: declared for a path that already exists on disk → Architect error."""
    import orchestration.pipeline as pl

    # Create the file so it "already exists"
    sample_root = tmp_path / "sample_repo" / "flaskbb"
    sample_root.mkdir(parents=True)
    existing = sample_root / "existing_module.py"
    existing.write_text("# exists")

    monkeypatch.setattr(pl, "REPO_ROOT", str(tmp_path))
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))

    task = pipeline.initialize_task("Test feature", task_id="test_overwrite")
    task["scoped_files"] = ["existing_module.py"]
    task["plan"] = "NEW FILE: existing_module.py\nDo something."

    task = pipeline.call_coding_agent(task)

    assert task["status"] == "blocked"
    coding_entries = [e for e in task["history"] if e["agent"] == "coding_agent"]
    assert coding_entries[0]["success"] is None


def test_pipeline_routes_blocked_task_straight_to_manager(monkeypatch, tmp_path):
    """When Coding Agent returns status=blocked, Testing/Review must be skipped."""
    monkeypatch.setattr(pipeline, "STATS_PATH", str(tmp_path / "agent_stats.json"))
    monkeypatch.setattr(pipeline, "RUN_HISTORY_PATH", str(tmp_path / "run_history.json"))
    import orchestration.pipeline as pl
    monkeypatch.setattr(pl, "REPO_ROOT", str(tmp_path))  # forces all scoped_files to fail

    testing_called = []
    review_called = []

    def fake_testing(task):
        testing_called.append(True)
        return task

    def fake_review(task):
        review_called.append(True)
        return task

    monkeypatch.setattr(pipeline, "call_testing_agent", fake_testing)
    monkeypatch.setattr(pipeline, "call_review_agent", fake_review)

    task = pipeline.run_pipeline("Blocked architect test", task_id="test_route_blocked")

    assert task["status"] == "blocked"
    assert len(testing_called) == 0, "Testing Agent must NOT be called when Coding is blocked"
    assert len(review_called) == 0, "Review Agent must NOT be called when Coding is blocked"


def test_append_history_accepts_none_success():
    """append_history must accept success=None (maps to JSON null)."""
    task = make_fresh_task()
    task = pipeline.append_history(task, "coding_agent", "blocked: architect error", None)
    assert task["history"][0]["success"] is None

